### PR TITLE
parse help output

### PR DESCRIPTION
**Pull request by mpal9000**
issue #92 

Those two scripts are inserting a parsed output of `6to5 --help` inside a "target" file. The "target" must contain a begin and an end marker comment.

"read-6to5-help.js" returns the help output to json, so you can also get it with ajax, but because the docs are created with jekyll there is "insert-6to5-help-output.js" script which conforms to the static nature of the site.

The formatting of `6to5 --help` output must be consistent, but it's easy to make changes in "read-6to5-help.js" if needed.

"insert-6to5-help-output.js" must be executable and `6to5-node` must be in the system's path.

So you can add `./_help-output/insert-6to5-help-output.js ./scripts/repl.js` to the `Makefile`.
I added the begin/end marker comments to "./scripts/repl.js" along with an `ignoredOptions` array.

Then inside "./scripts/repl.js" -> `Options()` you can do something like this:
```javascript
var html = [];

for (var i = 0, l = helpOutput.options.length; i < l; ++i) {
  var option = helpOutput.options[i];
  if (~ignoredOptions.indexOf(option.name)) continue;
  
  html.push(...);
}
```

You can also create a backup of "./scripts/repl.js" before running "./_help-output/insert-6to5-help-output.js".

The json output of "read-6to5-help.js" is like this:
```javascript
{ usage: [],
  options:
   [ { name: 'help', desc: 'output usage information' },
     { name: 'source-maps-inline',
       desc: 'Append sourceMappingURL comment to bottom of code' },
     { name: 'source-maps',
       desc: 'Save source map alongside the compiled code' },
     { name: 'filename',
       argName: 'filename',
       desc: 'Filename to use when reading from stdin - this will be used in source-maps, errors etc [stdin]' },
     { name: 'watch', desc: 'Recompile files on changes' },
     { name: 'runtime',
       desc: 'Replace 6to5 declarations with references to a runtime' },
     { name: 'experimental',
       desc: 'Enable experimental support for proposed ES7 features' },
     { name: 'playground', desc: 'Enable playground support' },
     { name: 'modules',
       argName: 'modules',
       desc: 'Module formatter type to use [common]' },
     { name: 'whitelist',
       argName: 'whitelist',
       desc: 'Whitelist of transformers to ONLY use' },
     { name: 'blacklist',
       argName: 'blacklist',
       desc: 'Blacklist of transformers to NOT use' },
     { name: 'optional',
       argName: 'list',
       desc: 'List of optional transformers to enable' },
     { name: 'loose',
       argName: 'list',
       desc: 'List of transformers to enable their loose mode' },
     { name: 'out-file',
       argName: 'out',
       desc: 'Compile all input files into a single file' },
     { name: 'out-dir',
       argName: 'out',
       desc: 'Compile an input directory of modules into an output directory' },
     { name: 'remove-comments',
       desc: 'Remove comments from the compiled code' },
     { name: 'indent', argName: 'width', desc: 'Indent width [2]' },
     { name: 'amd-module-ids',
       desc: 'Insert module id in AMD modules' },
     { name: 'module-ids', desc: 'Insert module id in modules' },
     { name: 'react-compat',
       desc: 'Makes the react transformer produce pre-v0.12 code' },
     { name: 'include-regenerator',
       desc: 'Include the regenerator runtime if necessary' },
     { name: 'keep-module-id-extensions',
       desc: 'Keep extensions when generating module ids' },
     { name: 'version', desc: 'output the version number' } ],
  transformers:
   [ { name: 'abstractReferences' },
     { name: 'arrayComprehension' },
     { name: 'arrowFunctions' },
     { name: 'asyncToGenerator', isOptional: true },
     { name: 'blockScopingTDZ', isOptional: true },
     { name: 'bluebirdCoroutines', isOptional: true },
     { name: 'classes' },
     { name: 'computedPropertyNames' },
     { name: 'constants' },
     { name: 'coreAliasing', isOptional: true },
     { name: 'defaultParameters' },
     { name: 'destructuring' },
     { name: 'exponentiationOperator' },
     { name: 'forOf' },
     { name: 'generatorComprehension' },
     { name: 'generators' },
     { name: 'letScoping' },
     { name: 'malletOperator' },
     { name: 'memoizationOperator' },
     { name: 'methodBinding' },
     { name: 'modules' },
     { name: 'objectGetterMemoization' },
     { name: 'objectSpread' },
     { name: 'propertyMethodAssignment' },
     { name: 'propertyNameShorthand' },
     { name: 'protoToAssign', isOptional: true },
     { name: 'react' },
     { name: 'restParameters' },
     { name: 'specBlockScopedFunctions' },
     { name: 'specMemberExpressionLiterals' },
     { name: 'specNoForInOfAssignment' },
     { name: 'specPropertyLiterals' },
     { name: 'specSetters' },
     { name: 'spread' },
     { name: 'templateLiterals' },
     { name: 'typeofSymbol', isOptional: true },
     { name: 'undeclaredVariableCheck', isOptional: true },
     { name: 'undefinedToVoid', isOptional: true },
     { name: 'unicodeRegex' },
     { name: 'useStrict' } ],
  moduleFormatters:
   [ { name: 'amd' },
     { name: 'amdStrict' },
     { name: 'common' },
     { name: 'commonStrict' },
     { name: 'ignore' },
     { name: 'system' },
     { name: 'umd' },
     { name: 'umdStrict' } ] }
```

### CODE REVIEW

**Comment by sebmck** [comment]
What use case do you have in mind?

**Comment by mpal9000** [comment]
Creating the html content of ".to5-repl-toolbar" dynamically, by using the inserted json help output.

**Comment by mpal9000** [comment]
Having the entire help output in a json `var`, lets you decide what the toolbar contains and how it looks like. Also the repl need js to be available, so the dynamic creation of html won't be a progressive-enhancement problem.

**Comment by sebmck** [comment]
It would've been easier to add a script in the main 6to5 repo that just used the internal APIs to build a list of options, module formatters and transformers instead of parsing the `6to5 --help` output.

**Comment by mpal9000** [comment]
Sure but it works like this too. It was easier for me to write a parser than read all the code of 6to5, because I have not so much time. It's just an idea, I have no problem if you won't pull it. If you want to close this and you have time to give some instructions for implementing it the right way (maybe in issue 92), I may find some time to do it in this week or somebody else.

**Comment by sebmck** [comment]
I really appreciate the time you've taken to do this. I'll detail in #92 when I get the time the best way to go about this. Also check out our [gitter room](https://gitter.im/6to5/6to5) if you have any questions. Thanks!

**Comment by mpal9000** [comment]
OK, thank you for the awesome tool!

**Comment by mpal9000** [comment]
it would be nice if `commander` could export the help to json

**Pull request closed without merging**
