### PR TITLE
Fix code url on REPL on Firefox

### PR DESCRIPTION
**Pull request by sparty02**

### CODE REVIEW

**Comment by thejameskyle** [comment]
@sparty02 Mind giving the commit a better description? Makes it easier to follow.

**Comment by sparty02** [comment]
@thejameskyle Sound better?

**Comment by thejameskyle** [comment]
heh, you don't have to be _so_ verbose, but thanks

**Comment by sparty02** [comment]
@thejameskyle LOL, I really wasn't trying to be snippy about it.... just getting used to contributing more....

**Comment by thejameskyle** [comment]
This actually doesn't appear to have fixed every issue in firefox.

**Comment by thejameskyle** [comment]
@sparty02 It's cool :smile:

**Comment by sparty02** [comment]
@thejameskyle I was actually thinking about this issue recently (in addition to how it relates to #44 that you opened) and I'm wondering if persisting the REPL input to the query fragment is the best approach.  This is kinda why I abstracted out the 'persistState' method in the REPL object so that it would be easier to reason about later.

One thought I had was to just base64 encode the whole thing into a string (vs doing the encodeUriComponent".  I dunno....

**Comment by thejameskyle** [comment]
@sparty02 I would be okay with base64-ing the code, but I think the query fragment works well otherwise.

We'll have to include a base64 implementation since btoa/atob aren't supported < IE10.

**Comment by sparty02** [comment]
@thejameskyle agreed....I'll take a look at this, probably tomorrow.

**Comment by thejameskyle** [comment]
Sure, thank you so much for the work you've been putting into this!

**Pull request merged**
