### PR TITLE
parseQuery should ignore irrelevant query params

### PR DESCRIPTION
**Pull request by sparty02**
Note: This will also "fix" bogus URLs coming in with invalid parms (upon persisting state)

### CODE REVIEW

**Comment by sparty02** [comment]
Ping @thejameskyle

**Comment by thejameskyle** [comment]
Whoops, sorry I left this here. Would you mind renaming these to `params`?

**Comment by sparty02** [comment]
@thejameskyle  No problem, done.

**Comment by thejameskyle** [comment]
Needs a rebase

**Comment by sparty02** [comment]
Done!

**Comment by thejameskyle** [comment]
Thanks!

**Pull request merged**
