### PR TITLE
modularize REPL

### PR DESCRIPTION
**Pull request by sparty02**
@thejameskyle via our recent convo, ping me with any questions/concerns.

### CODE REVIEW

**Comment by thejameskyle** [comment]
@sparty02 Could you rebase this?

**Comment by sparty02** [comment]
@thejameskyle Done.

**Comment by thejameskyle** [comment]
Can you set up the default options?
- Experimental = true
- Playground = true
- Loose Mode = false
- Evaluate = true

**Comment by sparty02** [comment]
@thejameskyle defaults added.

**Comment by thejameskyle** [comment]
:+1:

**Comment by thejameskyle** [comment]
Thanks @sparty02!

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
