### PR TITLE
fix core-js aliasing link in FAQ

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by sebmck** [comment]
Thanks!

**Comment by cvrebert** [comment]
May I recommend that you use some sort of tool to ensure that none of these sorts of cross-references become broken like this in the future?

**Comment by sebmck** [comment]
@cvrebert Probably, do you know of any?

**Comment by cvrebert** [comment]
Not offhand, but I'm sure they exist.

**Pull request merged**
