### PR TITLE
Add browser compatibility to the FAQ page.

### PR DESCRIPTION
**Pull request by jmeas**
I would wager that this is **the** question people will be most interested in. As such, I've placed it at the top of the FAQ. If you think it'd be better placed somewhere else on the page, nbd, just lemme know and I can move it down.

### CODE REVIEW

**Comment by sebmck** [comment]
Great, thanks!

**Comment by thejameskyle** [comment]
The button changed as I was clicking on it...

**Comment by jmeas** [comment]
:+1:

**Comment by sebmck** [comment]
@thejameskyle 🏃💨

**Pull request merged**
